### ISSUE TITLE
Startup failed

### ISSUE THREAD

**Issue by bg2vcj** [spencershepard/RotorOps#72]
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 449, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 444, in _make_request
  File "http\client.py", line 1374, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 279, in _read_status
  File "socket.py", line 705, in readinto
  File "ssl.py", line 1274, in recv_into
  File "ssl.py", line 1130, in read
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 770, in reraise
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 451, in _make_request
  File "urllib3\connectionpool.py", line 340, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='dcs-helicopters.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MissionGenerator.py", line 987, in loadModules
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 532, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='dcs-helicopters.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MissionGenerator.py", line 1100, in <module>
  File "MissionGenerator.py", line 989, in loadModules
TypeError: 'Logger' object is not callable

**Comment by spencershepard** [comment]
Hi @bg2vcj this looks like an internet connection or firewall issue.  We should display a clear error message for this, so I will leave this issue open for that. 

Please make sure you have an internet connection and that windows firewall isn't blocking the app.
